version: '3.7'

services:

#  nginx:
#    depends_on:
#      - frontend
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: ./nginx
#    ports:
#      - "3050:80"
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    command: --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Gemalto01!
      MONGO_INITDB_DATABASE: dpg
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#    healthcheck:
#      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/dpg --quiet
#      interval: 10s
#      timeout: 10s
#      retries: 5
#      start_period: 40s
      
  frontend:
    stdin_open: true
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./fakebank
    volumes:
      - /app/node_modules
      - ./fakebank:/app
    ports:
      - 3050:3000
      
  api:
    environment:
      CMIP: https://20.127.6.212
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./dpgBankDemo
    ports:
      - 8080:8080
#    depends_on:
#      mongodb:
#        condition: service_healthy
      
  proxy:
    container_name: proxy
    build:
      dockerfile: Dockerfile
      context: ./apiProxy
    ports:
      - 8081:8081

  ciphertrust:
    image: thalesciphertrust/ciphertrust-data-protection-gateway:latest
    container_name: ciphertrust
    environment:
      - REG_TOKEN=wIhkyNwg4u4UPltBU1JDHo2LqM25TZmu6TXk9Fg8GZ7PQ9UDWZzuoJJX94B56T59
      - DESTINATION_URL=http://api:8080
      - DPG_PORT=9005
      - TLS_ENABLED=false
      - KMS=20.127.6.212
    ports:
      - 9005:9005
      
networks:
  db_net:
    driver: bridge