version: '3.1'

services:

  nginx:
    depends_on:
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
      
  frontend:
    stdin_open: true
    container_name: frontend
    build:
      dockerfile: Dockerfile
      context: ./fakebank
    volumes:
      - /app/node_modules
      - ./fakebank:/app
      
  api:
    environment:
      CMIP: https://20.127.6.212
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./dpgBankDemo
    ports:
      - 8080:8080

  ciphertrust:
    image: thalesciphertrust/ciphertrust-data-protection-gateway:latest
    container_name: ciphertrust
    environment:
      - REG_TOKEN=AynX6XkHFREqJ1JWkTduIa91lmQ1AaqnDhUszgRz412lL9p9jtBKcUOODnkenIfH
      - DESTINATION_URL=http://nextjs:3000
      - DPG_PORT=9005
      - TLS_ENABLED=false
      - KMS=20.127.6.212
    ports:
      - 9005:9005

networks:
  db_net:
    driver: bridge