networks:
  db_net:
    driver: bridge
services:
  api:
    environment:
      CMIP: https://20.127.6.212
    ports:
      - 8080:8080
    build:
      context: ./dpgBankDemo
      dockerfile: Dockerfile
    container_name: api
  ciphertrust:
    environment:
      - REG_TOKEN=yMldtRw3KTydlkZVztUqQ1wxmse8KfqC9Pbo2LEEHk4MtkxEY1Ok98ErgFKa6TJR
      - DESTINATION_URL=http://api:8080
      - TLS_ENABLED=false
      - KMS=20.127.6.212
      - DPG_PORT=9005
    ports:
      - 9005:9005
    container_name: ciphertrust
    image: thalesciphertrust/ciphertrust-data-protection-gateway:latest
  frontend:
    build:
      context: ./fakebank
      dockerfile: Dockerfile
    ports:
      - 3050:3000
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./fakebank:/app
    container_name: frontend
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Gemalto01!
      MONGO_INITDB_DATABASE: dpg
    command: --quiet
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: mongodb
  proxy:
    ports:
      - 8081:8081
    build:
      context: ./apiProxy
      dockerfile: Dockerfile
    container_name: proxy
version: "3.7"
